### ISSUE TITLE
USB device not detected

### ISSUE THREAD

**Issue by ArminJo** [sanbeg/MicronucleusArduino#1]
Hi
I changed last line of launcer to $exec "/home/linux/sloeber/arduinoPlugin/packages/digistump/tools/micronucleus/2
.0a4/micronucleus" --type "$type" --timeout $timeout --run --no-ansi "$file"
to ensure the rigt binary was called.
**But nothing happened.**

When switching to the old binary with the same launcher I get:
```
Warning: device with unknown new version of Micronucleus detected.
This tool doesn't know how to upload to this new device. Updates may be available.
Device reports version as: 2.5
```
after attaching the digispark board.
The command is:
`Launching/home/linux/sloeber//arduinoPlugin/packages/digistump/tools/micronucleus/2.0a4/launcher -cdigispark --timeout 60 -Uflash:w:/home/linux/WORKSPACE_SLOEBER/BlinkTest/Release/BlinkTest.hex:i `

I am running on a 64 bit Linux Mint 20 Cinnamon

**Comment by sanbeg** [comment]
This script should be unaffected by which version of the binary is called.  Could you try running with the `-n` option, i.e. 
`launcher -n  -cdigispark --timeout 60 -Uflash:w:/home/linux/WORKSPACE_SLOEBER/BlinkTest/Release/BlinkTest.hex:i`

This will echo the command instead of running it, so you can verify that the expected command line is produced.

I did try pointing the script at a Sloeber installation that I happened to have, with a dummy hex file and no board plugged in just to see that it would call the binary, and that worked as expected for me.

**Comment by ArminJo** [comment]
Hi,
I added an echo before the exec and I get now:
```
Launching/home/linux/sloeber//arduinoPlugin/packages/digistump/tools/micronucleus/2.0a4/launcher -cdigispark --timeout 60 -Uflash:w:/home/linux/WORKSPACE_SLOEBER/BlinkTest/Release/BlinkTest.hex:i 
Output:
Plug in or reset device now (will timeout in 60 seconds)...
/home/linux/sloeber/arduinoPlugin/packages/digistump/tools/micronucleus/2.0a4/micronucleus --type intel-hex --timeout 60 --run --no-ansi /home/linux/WORKSPACE_SLOEBER/BlinkTest/Release/BlinkTest.hex
```
and after the timeout:
```
> Please plug in the device ... 
> Press CTRL+C to terminate the program.
> Device search timed out
```
But the device was not found (in contrast to the original micronucleus version)

**Comment by sanbeg** [comment]
I'm not sure that you needed to make modifications to the script.  By default, it runs the micronucleus binary from the same directory as the script, which seems like what you want.  There is also a `-n` option to enable a dry run mode, which will automatically add the echo, in place of exec.

Which micronucleus binary are you testing?  Was that bundled with Sloeber?  I have seen that the various cores and IDEs tend to bundle very old versions of the binary, which does tend to cause issues.

**Comment by ArminJo** [comment]
The old old binary giving `Warning: device with unknown new version of Micronucleus detected` is the one bundled with sloeber.
The new one not able to detect the device is yours.
I mentioned the old one only to show that there is no fault at my usb connections, since the old one can detect the plugged in device!

**Comment by sanbeg** [comment]
Are you referring to the binary in this repo, or from my PR?  The one in this repo was built from https://github.com/micronucleus/micronucleus/releases/tag/2.04 without code modifications.

I have tested both on Linux Mint, and haven't seen any issues so far.  I'll double check and see if I can reproduce it.

**Comment by ArminJo** [comment]
I use the binary from your repo. Does it detect a device plugged in on arbitrary ports on your system?
Maybe the code in micronucleus is not the one delivered as binary.

**Comment by sanbeg** [comment]
I haven't seen any problems with it on my system.  I was assuming that just running make from the release would produce a usable binary.  Maybe you could try compiling the same version on your system, and see if that works, and if there's some difference in how they are linked.

**Comment by ArminJo** [comment]
Thanks, everythig now works fine!
